In [26]:
import pandas as pd
import numpy as np

In [68]:
# Shift data so that trip ends are on separate row that trip starts
# This allows spider line mapping in tableau

df = pd.read_excel(r'J:\Projects\Surveys\HHTravel\Survey2017\Data\Dataset from RSG 180307\trips_52493_with_weights.xlsx',
                sheetname='trips_52493_with_weights')

In [3]:
for i in df.columns:
    print i

recid
personid
hhid
pernum
tripnum
tottrip1
tottrip2
last
daynum
hhgroup
land_use
origin_name
origin_address
origin_lat
origin_lng
dest_name
dest_address
dest_lat
dest_lng
depart_time_mam
depart_time_hhmm
depart_time_timestamp
arrival_time_mam
arrival_time_hhmm
arrival_time_timestamp
reported_duration
google_duration
trip_path_distance
speed_mph
a_dur
o_purp
o_purp_other
d_purp
d_purp_other
mode_1
mode_2
mode_3
mode_4
travelers_hh
travelers_nonhh
travelers_total
driver
hhmember1
hhmember2
hhmember3
hhmember4
hhmember5
hhmember6
hhmember7
hhmember8
hhmember9
hhmember_none
mode_acc
mode_egr
park
park_type
park_pay
transit_system_1
transit_system_2
transit_system_3
transit_system_4
transit_system_5
transit_line_1
transit_line_2
transit_line_3
transit_line_4
transit_line_5
pool_start
change_vehicles
park_ride_area_start
park_ride_area_end
park_ride_lot_start
park_ride_lot_end
toll
toll_pay
taxi_type
taxi_pay
bus_type
bus_pay
bus_cost_dk
ferry_type
ferry_pay
ferry_cost_dk
rail_type
rail_pay
rail_cost_dk
air_type
air_pay
airfare_cost_dk
svy_complete
traveldate
dayofweek
copied_trip
completed_at
revised_at
revised_count
google_durationSEC
trip_path_distancemtr
user_merged
user_split
analyst_merged
analyst_split
flag_teleport
proxy_added_trip
nonproxy_derived_trip
child_trip_location_tripid
linked_flag
num_trips_linked
combined_modes
hh_day_complete
nwkdays
hh_day_wt_final
hh_day_wt_adjusted
trip_wt_final

In [69]:
# Split record into a row for origins and destinations
o_fields = ['origin_name','origin_address','origin_lat','origin_lng',
           'o_purp','o_purp_other','arrival_time_mam','arrival_time_hhmm',
           'arrival_time_timestamp']
d_fields = ['dest_name','dest_address','dest_lat','dest_lng',
           'd_purp','d_purp_other','depart_time_mam','depart_time_hhmm',
           'depart_time_timestamp']

In [70]:
# origin rows with 0 values for d_fields
df_o = df.copy()
df_o['trip_end'] = 'origin'
df_o[d_fields] = np.nan

df_d = df.copy()
df_d['trip_end'] = 'destination'
df_d[o_fields] = np.nan

df_out = df_o.append(df_d)

In [80]:
df_out.to_excel(r'J:\Projects\Surveys\HHTravel\Survey2017\Data\Dataset from RSG 180307\trips_52493_with_weights_pivot.xlsx', index=False)

In [72]:
a = df_o.append(df_d)

In [73]:
df_out[df_out['recid'] == 'D00001']['origin_lat']

0    47.6952
0        NaN
Name: origin_lat, dtype: object

In [49]:
df_o[d_fields].ix[:] = 0

In [52]:
df_o[d_fields] = 0

In [53]:
df_o[d_fields]

,dest_name,dest_address,dest_lat,dest_lng,d_purp,d_purp_other,depart_time_mam,depart_time_hhmm,depart_time_timestamp
0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
52463,0,0,0,0,0,0,0,0,0
52464,0,0,0,0,0,0,0,0,0
52465,0,0,0,0,0,0,0,0,0
52466,0,0,0,0,0,0,0,0,0
52467,0,0,0,0,0,0,0,0,0
52468,0,0,0,0,0,0,0,0,0
52469,0,0,0,0,0,0,0,0,0
52470,0,0,0,0,0,0,0,0,0
52471,0,0,0,0,0,0,0,0,0
52472,0,0,0,0,0,0,0,0,0
52473,0,0,0,0,0,0,0,0,0
52474,0,0,0,0,0,0,0,0,0
52475,0,0,0,0,0,0,0,0,0
52476,0,0,0,0,0,0,0,0,0
52477,0,0,0,0,0,0,0,0,0
52478,0,0,0,0,0,0,0,0,0
52479,0,0,0,0,0,0,0,0,0
52480,0,0,0,0,0,0,0,0,0
52481,0,0,0,0,0,0,0,0,0
52482,0,0,0,0,0,0,0,0,0
52483,0,0,0,0,0,0,0,0,0
52484,0,0,0,0,0,0,0,0,0
52485,0,0,0,0,0,0,0,0,0
52486,0,0,0,0,0,0,0,0,0
52487,0,0,0,0,0,0,0,0,0
52488,0,0,0,0,0,0,0,0,0
52489,0,0,0,0,0,0,0,0,0
52490,0,0,0,0,0,0,0,0,0
52491,0,0,0,0,0,0,0,0,0
52492,0,0,0,0,0,0,0,0,0