In [1]:
import pandas as pd

In [2]:
hh = pd.read_csv(r'J:\Projects\Surveys\HHTravel\Survey2015\Data\Household\PSRC2015_HH_2015-07-27_V1.1.csv')

In [4]:
trip = pd.read_csv(r'J:\Projects\Surveys\HHTravel\Survey2015\Data\Trips\PSRC2015_Trip_2015-07-27_V1.4.csv')

c:\Users\Brice\AppData\Local\Continuum\Anaconda\lib\site-packages\pandas\io\parsers.py:1170: DtypeWarning: Columns (57) have mixed types. Specify dtype option on import or set low_memory=False.
  data = self._reader.read(nrows)

In [7]:
trip_hh = pd.merge(trip,hh,on='hhid')

In [11]:
trip_hh.groupby('mode').sum()

,chk,order,personID,tripID,hhid,pernum,tripnum,tottrip,last,olat,...,contact_email,contact_phonecall,contact_text,incentive_type,incentive_amt,giftcard_mail,call_center,user_ismobiledevice,foreign_language,participate
mode,,,,,,,,,,,,,,,,,,,,,
1,89,77263464,10881203176707,1088120317695738,108812031665,10207,25038,44134,1620,356744.849801,...,6218,976,687,11135,84700,748,660,855,52,3179
2,18,48696291,6874167812254,687416781243314,68741678020,10254,17914,28685,1263,225209.911425,...,4061,476,490,6760,59610,313,269,669,18,1901
3,3,12227066,1794368826687,179436882673766,17943688247,1987,5066,8291,195,58563.931953,...,964,212,129,1820,14290,178,146,129,3,465
4,NaN,140677,22765517826,2276551782633,227655178,26,33,56,7,705.198546,...,16,0,0,21,200,NaN,0,5,0,2
5,1,562748,94576538696,9457653869778,945765386,96,178,372,7,3133.937707,...,53,9,9,95,740,4,4,4,2,15
6,1,2848876,442655990337,44265599034644,4426559899,437,944,1693,71,14661.659361,...,275,10,34,414,3510,8,8,39,2,90
7,14,33833471,5396015642221,539601564226391,53960156365,5623,14091,24731,679,177911.957950,...,3242,312,379,5318,43350,246,255,406,21,1129
8,28,11907657,1996866465499,199686646554096,19968664636,1899,4196,7582,290,65999.359055,...,1153,191,136,1983,16090,140,157,126,8,424
9,NaN,785254,123163053612,12316305361500,1231630535,112,300,566,8,4023.792195,...,73,2,15,116,940,NaN,0,10,0,33
10,3,664627,88821986086,8882198608820,888219860,86,220,400,10,2921.979251,...,51,8,4,83,660,6,6,3,0,28
11,NaN,33742,4330884205,433088420513,43308842,5,13,22,NaN,142.502562,...,2,1,0,4,30,1,1,1,0,1
12,3,2295712,330525268474,33052526847819,3305252677,774,419,791,63,10837.404149,...,196,24,26,332,3200,18,17,36,2,94
13,NaN,239797,45826657849,4582665785008,458266578,49,108,162,12,1487.870690,...,27,2,5,45,350,1,1,5,2,7
14,NaN,151980,20441978322,2044197832234,204419783,22,34,53,7,644.378340,...,12,2,0,16,210,2,0,0,0,7
15,2,625011,110386902629,11038690263102,1103869025,129,202,394,5,3623.799476,...,61,10,6,104,930,7,7,1,0,18
16,1,400436,66268957172,6626895717304,662689571,72,104,165,15,1946.541216,...,39,5,4,61,490,2,4,8,1,15
17,NaN,105943,14601323016,1460132301633,146013230,16,33,59,4,494.654481,...,9,1,1,17,100,1,1,1,0,5

In [21]:
pd.pivot_table(trip_hh, values='expwt_final', columns='h_rgc_name', aggfunc='sum')

KeyError: 'expwt_final'